pipeline:
    build:
        image: golang
        commands:
            - go version
            - go get github.com/gorilla/mux
            - go get github.com/lib/pq
            - go test -v

service:
    postgres:
        image: postgres:9.4.5
        environment:
            - POSTGRES_USER=myapp
