pipeline:
  build:
    image: golang
    environment:
      - APP_DB_USERNAME=gorest
      - APP_DB_PASSWORD=gorest
      - APP_DB_NAME=gorest
    commands:
      - go version
      - go get github.com/gorilla/mux
      - go get github.com/lib/pq
      - go build
      - go test

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=gorest
      - POSTGRES_PASSWORD=gorest
      - POSTGRES_DB=gorest
